site_name: test
site_url: https://xenthox.github.io/mkdocs
theme:
  name: material
  font:
    text: Roboto

  features:
  #  - navigation.tabs
  #  - navigation.tabs.sticky
    - navigation.sections
 #   - toc.integrate
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: teal
      accent: teal

nav:
  - Welcome: index.md
  - Incentive Testnet:
    - Introduction: testnet-introduction.md
    - Full-Chain Node: setup-and-run-a-stratos-chain-full-node.md
    - Become a Validator: how-to-become-a-validator.md
    - SDS Resource Node: setup-and-run-a-sds-resource-node.md
  - Stratos Full-Chain:
    - stchaind Commands Part 1: stchaind-commands-part-1.md
    - stchaind Commands Part 2: stchaind-commands-part-2.md
    - gRPC Queries: stratos-chain-grpc-queries.md
    - REST APIs: stratos-chain-rest-apis.md
  - Stratos Resource Node:
    - ppd Commands: ppd-terminal-subcommands.md
    - SDS RPC: sds-rpc-for-file-operation.md

plugins:
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/chrome
      link: https://thestratos.org
    - icon: fontawesome/brands/telegram
      link: https://t.me/StratosCommunity
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/tpQGpC2nMh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Stratos_Network 
    - icon: fontawesome/brands/medium
      link: https://stratos-network.medium.com/ 

markdown_extensions:
  - toc:
      permalink: "🔗&#xFE0E;"
      title: On this page
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - meta

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js        

copyright: Copyright
