site_name: Stratos Documentation
site_url: https://xenthox.github.io/mkdocs
theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  logo: assets/logo.png
  favicon: assets/favicon.ico

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      primary: teal
      accent: teal

nav:
  - Home: index.md
  - Testnet:
    - Introduction: docs-testnet/introduction.md
    - Changes in Tropos-5: docs-testnet/tropos-5-changes.md
    - Rewards Distribution: docs-testnet/incentive-rewards-distribution.md
    - Migrate Rewards: docs-testnet/migrate-rewards.md
  - Validator Node:
    - HOWTOs:
      - Full-Chain Node: docs-validator-node/setup-and-run-a-stratos-chain-full-node.md
      - Become a Validator: docs-validator-node/how-to-become-a-validator.md
    - Operating:
      - stchaind Commands Part 1: docs-validator-node/stchaind-commands-part-1.md
      - stchaind Commands Part 2: docs-validator-node/stchaind-commands-part-2.md
      - gRPC Queries: docs-validator-node/stratos-chain-grpc-queries.md
      - REST APIs: docs-validator-node/stratos-chain-rest-apis.md
  - Resource Node:
    - HOWTOs:
      - SDS Resource Node: docs-resource-node/setup-and-run-a-sds-resource-node.md
    - Operating:
      - ppd Commands: docs-resource-node/ppd-terminal-subcommands.md
      - SDS RPC: docs-resource-node/sds-rpc-for-file-operation.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/chrome
      link: https://thestratos.org
    - icon: fontawesome/brands/telegram
      link: https://t.me/StratosCommunity
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/tpQGpC2nMh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Stratos_Network 
    - icon: fontawesome/brands/medium
      link: https://stratos-network.medium.com/ 

markdown_extensions:
  - toc:
      permalink: "🔗&#xFE0E;"
      title: On this page
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - meta
  - tables

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js        

copyright: <p> &copy; 2021-<script>document.write(new Date().getFullYear())</script> Stratos</p>
